version: "3"
services:
  db:
    image: postgres:14.3
    environment:
      POSTGRES_DB: task
      POSTGRES_USER: pavel
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
  server:
    build: .
    depends_on:
      - db
    ports:
      - "5050:5050"
    user: root
    links: 
      - db